# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.0"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 7"
# Use postgresql as the database for Active Record
gem "pg" # , ">= 0.18", "< 2.0"
# Use Puma as the app server
gem "puma"
# Use SCSS for stylesheets
gem "sass-rails"
gem "sassc"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder" # , "~> 2.5"
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.1.0", require: false

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

gem "bulma-rails"
gem "counter_culture"
gem "devise"
gem "devise-jwt"
gem "high_voltage"
gem "httparty"
gem "nokogiri"
gem "pundit"
gem "rolify"
gem "simple_form"
gem "slim-rails"
gem "strong_migrations"

group :development, :test do
  gem "annotate"
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "database_consistency", require: false
  gem "factory_bot_rails"
  gem "faker"
  gem "fuubar"
  # gem 'guard', '~> 2', require: false
  # gem 'guard-brakeman', require: false
  # gem 'guard-bundler', require: false
  # gem 'guard-fasterer', require: false
  # gem 'guard-rspec', require: false
  # gem 'guard-rubocop', require: false
  gem "heavens_door"
  gem "rails_logtruncate"
  gem "rb-readline"
  gem "rspec-rails"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "spring-commands-rspec"
  gem "terminal-notifier"
  gem "terminal-notifier-guard"
end

group :development do
  # gem 'listen' # , '>= 3.0.5', '< 3.2'
  gem "rails_dev_ssl"
  gem "spring"
  gem "spring-watcher-listen" # , '~> 2.0.0'
  gem "standard"
  gem "web-console", ">= 3.3.0"
end

group :test do
  gem "capybara", ">= 2.15"
  gem "pundit-matchers"
  gem "shoulda-matchers"
  gem "simplecov"
  gem "webdrivers", require: false
end
