Layout/AlignHash:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
Metrics/BlockLength:
  Exclude:
    - Guardfile
    - lib/tasks/*
Metrics/LineLength:
  Max: 92
  Exclude:
    - Gemfile
    - Guardfile
    - Rakefile
    - config/environments/*
    - config/initializers/*
Naming/FileName:
  Exclude:
    - Guardfile
    - Gemfile
Rails:
  Enabled: true
Rails/TimeZone:
  EnforcedStyle: strict
Rails/Date:
  EnforcedStyle: strict
Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Exclude:
    - app/helpers/*
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - config/**/*
