Layout/HashAlignment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
Metrics/BlockLength:
  Exclude:
    - Guardfile
    - lib/tasks/*
    - spec/**/*
Layout/LineLength:
  Max: 92
  Exclude:
    - Gemfile
    - Guardfile
    - Rakefile
    - app/views/**/*.jbuilder
    - config/environments/*
    - config/initializers/*
    - config/routes.rb
    - spec/**/*
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Naming/FileName:
  Exclude:
    - Guardfile
    - Gemfile
Rails:
  Enabled: true
Rails/Date:
  EnforcedStyle: strict
Rails/FilePath:
  EnforcedStyle: arguments
Rails/HasAndBelongsToMany:
  Exclude:
    - app/models/role.rb
Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/application_controller.rb
Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
Rails/TimeZone:
  EnforcedStyle: strict
Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Exclude:
    - app/helpers/*
    - app/controllers/*
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - app/policies/*
    - config/**/*
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
