name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 3
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build and test with Rake
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec
